# Generated by Django 6.0.6 on 2026-06-28 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('MAIN', 'Main'), ('SIDE', 'Side'), ('DRINK', 'Drink')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MealDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealDealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsthedeal_app.item')),
                ('meal_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='whatsthedeal_app.mealdeal')),
            ],
        ),
        migrations.AddField(
            model_name='mealdeal',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='meal_deals', through='whatsthedeal_app.MealDealItem', to='whatsthedeal_app.item'),
        ),
        migrations.CreateModel(
            name='MealDealSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('MAIN', 'Main'), ('SIDE', 'Side'), ('DRINK', 'Drink')], max_length=10)),
                ('required', models.BooleanField(default=True)),
                ('min_items', models.PositiveIntegerField(default=1)),
                ('max_items', models.PositiveIntegerField(default=1)),
                ('meal_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='whatsthedeal_app.mealdeal')),
            ],
        ),
        migrations.AddField(
            model_name='mealdealitem',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='whatsthedeal_app.mealdealslot'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('meal_deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='whatsthedeal_app.mealdeal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='whatsthedeal_app.post')),
            ],
        ),
        migrations.AddField(
            model_name='mealdeal',
            name='supermarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_deals', to='whatsthedeal_app.supermarket'),
        ),
        migrations.AddField(
            model_name='item',
            name='supermarkets',
            field=models.ManyToManyField(blank=True, related_name='items', to='whatsthedeal_app.supermarket'),
        ),
        migrations.AddConstraint(
            model_name='mealdealslot',
            constraint=models.UniqueConstraint(fields=('meal_deal', 'slot_type'), name='unique_meal_deal_slot_type'),
        ),
        migrations.AddConstraint(
            model_name='mealdealitem',
            constraint=models.UniqueConstraint(fields=('meal_deal', 'item', 'slot'), name='unique_meal_deal_item_slot'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_like'),
        ),
    ]
