# Generated by Django 6.0.6 on 2026-06-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsthedeal_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealdeal',
            name='description',
        ),
    ]
