# Generated by Django 6.0.6 on 2026-06-29 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsthedeal_app', '0004_preference_remove_dislike_unique_user_post_dislike_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='preference',
            constraint=models.UniqueConstraint(fields=('user', 'post', 'value'), name='unique_user_post_preference'),
        ),
        migrations.AddConstraint(
            model_name='preference',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 1), ('value__lte', 2)), name='value_between_1_and_2'),
        ),
        migrations.AddConstraint(
            model_name='preference',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='value_non_negative'),
        ),
    ]
